PlatformSamples/AspNetCoreMvc/Models/ErrorViewModel.cs
using System;

namespace AspNetCoreMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PlatformSamples/AspNetCoreMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using AspNetCoreMvc.Models;
using Ooui;
using Ooui.AspNetCore;

namespace AspNetCoreMvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index ()
        {
            return View ();
        }

        public IActionResult About ()
        {
            ViewData["Message"] = "Ooui is a mini web framework to make programming interactive UIs easy.";

            return View ();
        }

        public IActionResult Contact ()
        {
            ViewData["Message"] = "Find us on github.";

            return View ();
        }

        public IActionResult Error ()
        {
            return View (new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PlatformSamples/AspNetCoreMvc/Controllers/SamplesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using AspNetCoreMvc.Models;
using Ooui;
using Ooui.AspNetCore;
using Samples;
using System.Collections.Concurrent;
using Ooui.Html;

namespace AspNetCoreMvc.Controllers
{
    public class SamplesController : Controller
    {
        public IActionResult Clicker ()
        {
            var count = 0;
            var head = new Heading { Text = "Click away!" };
            var label = new Label { Text = "0" };
            var btn = new Button { Text = "Increase" };
            btn.Click += (sender, e) => {
                count++;
                label.Text = count.ToString ();
            };
            var div = new Div ();
            div.AppendChild (head);
            div.AppendChild (label);
            div.AppendChild (btn);
            return new ElementResult (div);
        }

        static readonly Lazy<List<Samples.ISample>> lazySamples =
            new Lazy<List<Samples.ISample>> ((() => {
                var sampleType = typeof (Samples.ISample);
                var asm = sampleType.Assembly;
                var sampleTypes = asm.GetTypes ().Where (x => x.Name.EndsWith ("Sample", StringComparison.Ordinal) && x != sampleType);
                var samples = from t in sampleTypes
                              let s = Activator.CreateInstance (t) as Samples.ISample
                              where s != null
                              orderby s.Title
                              select s;
                return samples.ToList ();
            }), true);

        static readonly ConcurrentDictionary<string, Element> sharedSamples =
            new ConcurrentDictionary<string, Element> ();

        public static List<Samples.ISample> Samples => lazySamples.Value;

        [Route ("/Samples/Run/{name}")]
        public IActionResult Run (string name, bool shared)
        {
            if (string.IsNullOrWhiteSpace (name) || name.Length > 128)
                return BadRequest ();

            var s = Samples.FirstOrDefault (x => x.Title == name);
            if (s == null)
                return NotFound ();

            var element = shared ? GetSharedSample (s) : s.CreateElement ();

            return new ElementResult (element, title: s.Title + " - Ooui Samples");
        }

        private Element GetSharedSample (ISample s)
        {
            if (sharedSamples.TryGetValue (s.Title, out var e))
                return e;
            e = s.CreateElement ();
            sharedSamples[s.Title] = e;
            return e;
        }

        [Route ("/shared-button")]
        public IActionResult SharedButton ()
        {
            return Run ("Button Counter", true);
        }
    }
}

PlatformSamples/AspNetCoreMvc/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Find out more <a href="https://github.com/praeclarum/Ooui">on github</a></p>

PlatformSamples/AspNetCoreMvc/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>


PlatformSamples/AspNetCoreMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ooui";
    var formsSamples = SamplesController.Samples.Where(x => x.Title.StartsWith("Xamarin.Forms "));
    var otherSamples = SamplesController.Samples.Where(x => !x.Title.StartsWith("Xamarin.Forms "));
}

<div class="row" style="margin-top:4em;">
    <div class="col-md-2">
        <img src="images/Icon.png" />
    </div>
    <div class="col-md-2">
        <h1>Ooui</h1>
        <p>Write interactive web apps in C# and F#</p>
        <p><a href="https://github.com/praeclarum/Ooui">Source Code on GitHub</a></p>
    </div>
</div>

<div class="row" style="margin-top:4em;">
    <div class="col-md-4">
        <h3>Xamarin.Forms Samples</h3>
        <ul>
			@foreach (var s in formsSamples) {
                <li>
				    <a asp-area="" asp-controller="Samples" asp-action="Run" asp-route-name="@s.Title">@s.Title.Substring(14)</a>
			    </li>
			}
        </ul>
    </div>
    <div class="col-md-4">
        <h3>Plain Web Samples</h3>
        <ul>
			@foreach (var s in otherSamples) {
                <li>
				    <a asp-area="" asp-controller="Samples" asp-action="Run" asp-route-name="@s.Title">@s.Title</a>
			    </li>
			}
        </ul>
    </div>
</div>

PlatformSamples/AspNetCoreMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ooui</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Ooui</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Ooui @(typeof(Ooui.Html.Element).Assembly.GetName().Version)</p>
            <p>&copy; 2017 - @DateTime.UtcNow.Year Frank A. Krueger</p>
            @{ var e = new Ooui.Html.Anchor ("https://github.com/praeclarum/Ooui", "π"); }
            <ooui element="e" />
            <!--Html.Ooui (e)-->
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>